create table if not exists public.contact_requests (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  full_name text not null,
  email text not null,
  message text not null,
  constraint contact_requests_pkey primary key (id)
) TABLESPACE pg_default;

create table public.countries (
  id integer generated by default as identity not null,
  name text not null,
  constraint countries_pkey primary key (id),
  constraint countries_name_key unique (name)
) TABLESPACE pg_default;

create table if not exists public.teams (
  "idTeam" bigint generated by default as identity not null,
  name text not null,
  "foundationYear" integer not null default 1824,
  countrie_id integer not null,
  full_name text null,
  constraint teams_pkey primary key ("idTeam"),
  constraint teams_countrie_id_fkey foreign KEY (countrie_id) references countries (id) on update CASCADE on delete CASCADE,
  constraint teams_name_unique unique(name)
) TABLESPACE pg_default;

create table if not exists public.player (
  id bigint generated by default as identity not null,
  "firstName" text not null,
  "backNumber" smallint not null,
  "lastName" text not null,
  "clubID" bigint null,
  "birthDate" date null,
  position text null,
  image text null,
  market_value real null default '0'::real,
  active boolean null default true,
  constraint player_pkey primary key (id),
  constraint player_clubID_fkey foreign KEY ("clubID") references teams ("idTeam") on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table if not exists public.transfers (
  id bigint generated by default as identity not null,
  "transferDate" date not null default now(),
  "playerID" bigint not null,
  "clubOrigin" bigint not null,
  "clubDestination" bigint not null,
  "marketValue" double precision not null,
  constraint transfers_pkey primary key (id),
  constraint transfers_clubDestination_fkey foreign KEY ("clubDestination") references teams ("idTeam"),
  constraint transfers_clubOrigin_fkey foreign KEY ("clubOrigin") references teams ("idTeam"),
  constraint transfers_playerID_fkey foreign KEY ("playerID") references player (id)
) TABLESPACE pg_default;


INSERT INTO "public"."countries" ("name")
VALUES ('United States'), ('Mexico'), ('Germany'), ('Spain'), ('England'), ('Italy'), ('Portugal'), ('France'), ('Netherlands');

INSERT INTO "public"."teams" ("name", "foundationYear", "countrie_id", "full_name")
VALUES ('FC Porto', 1924, 7, 'Andre Vilas Boas'), ('FC Barcelona', 1900, 4, null),
('Real Madrid', 1900, 4, 'Perez'), ('FC Bayern München', 1900, 3, 'Hoeneß'),
('Sport Lissboa Benfica ', 1904, 7, 'Rui Costa'), ('Paris Saint Germain', 1900, 8, null),
('Manchester United', 1900, 5, null), ('PSV Eindhoven', 1900, 9, null),
('Hamburger Sport Verein', 1887, 3, null);

INSERT INTO "public"."player" ("firstName", "backNumber", "lastName", "clubID", "birthDate", "position", "image", "market_value", "active")
VALUES ('Diogo', 99, 'Costa', 1, '1999-09-19', 'goalkeeper', 'https://img.uefa.com/imgml/TP/players/17/2026/324x324/250076675.jpg', 0, true),
('Luis', 7, 'Figo', 3, '1972-11-04', 'midfield', 'https://img.a.transfermarkt.technology/portrait/big/3446-1570440028.jpg?lm=4711', 60, true);