import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://rzjwdxbpwovwueflpwsp.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6andkeGJwd292d3VlZmxwd3NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjk2MTk4MDYsImV4cCI6MjA0NTE5NTgwNn0.dJumPgbUh6Ru37DXLxEkq_Lx3_9OEm0gPG6fOaz3agY')